---
title: "ANALYSIS ON COVID-19"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(plotly)
library(tidyverse)
library(flexdashboard)
library('lubridate')
library(dplyr)
library(ggplot2)
```

## Column {data-width="300"}

### World Wide Cases

```{r}
covid <- read.csv("D:\\Semester - 6\\INT 232\\R Project\\country_daywise.csv")
daywise <- read.csv("D:\\Semester - 6\\INT 232\\R Project\\daywise.csv")
covid$Date <- ymd(covid$Date)
covid <- arrange(covid,Date)
daywise$Date <- ymd(daywise$Date)
fig <- plot_ly(daywise, x=~Date)
fig <- fig %>% add_trace(y=~Confirmed, name='Confirmed', mode='lines', type='scatter')
fig <- fig %>% add_trace(y=~Recovered, name ='Recovered', mode='lines',type='scatter')
fig <- fig %>% add_trace(y=~Deaths, name ='Deaths', mode='lines',type='scatter')
cnf <- "#893ea6"
rec<- "#ff2e63"
dth <- "#21bf73"
act <- "#fe9801"
fig <- plot_ly(daywise, x=~Date)  
cnf.line <- list(color = cnf , width = 4)
dth.line <- list(color = dth , width = 4)

rec.line <- list(color = rec ,width = 4)
act.line <- list(color = act ,width = 4)
fig <- fig %>% add_trace(y=~Confirmed, name='Confirmed', mode='lines', type='scatter',line=cnf.line)
fig <- fig %>% add_trace(y=~Recovered, name ='Recovered', mode='lines',type='scatter',line=rec.line)
fig <- fig %>% add_trace(y=~Deaths, name ='Deaths', mode='lines',type='scatter',line=dth.line)
fig <- fig %>% layout(title = 'Total Worldwide Corona Cases',
                      xaxis = list(title='Date'),
                                   yaxis = list(title='Teotal Cases'))



fig
```

### Anaysis on US

```{r}
US <- covid %>% filter(Country=='US') %>% arrange(Date)
fig1 <- plot_ly(US,x=~Date,y=~Confirmed,type='scatter',mode='lines',name = 'Confirmed Cases')
fig2 <- plot_ly(US,x=~Date,y=~Recovered,type='scatter',mode='lines',name = 'Recovered Cases')
fig3 <- plot_ly(US,x=~Date,y=~Deaths,type='scatter',mode='lines',name = 'Deaths Cases')
subplot(fig1,fig2,fig3,nrows=2,shareX = F)
```

## Column {data-width="300"}

### top 10 country

```{r}
latest <- covid %>% filter(Date==max(Date)) %>% arrange(desc(Confirmed))
top10 <- latest %>% slice(1:10)
top10$Country <- factor(top10$Country,levels = c(as.character(top10$Country)))
values <- as.character(top10$Confirmed)
plot_ly(top10, x=~Country, y =~Confirmed ,type ='bar',names='Confirmed cases',
        text=values,textposition='auto',
        marker= list(color=heat.colors(n=10),
                     line=list(color='magneta',width=0)))
```

### Deaths VS Confirmed

```{r}
plot_ly(data = top10, x =~Confirmed,
        y=~Deaths,type='scatter',
        mode='markers',color =~Country,
        colors =terrain.colors(n=10) ,
        size =~Confirmed,
        marker=list(size=~1e-4*Deaths))
```


























